openapi: 3.0.0
info:
  title: "AI 요약 업데이트 API"
  description: "프론트엔드에서 AI 서비스를 호출하여 생성된 요약 정보(aiSummary, difficulty, estimatedTime)를 백엔드에 저장하는 API입니다."
  version: "1.0.0"

servers:
  - url: "http://localhost:8080/api/v1"
    description: "로컬 개발 서버"

tags:
  - name: Notes
    description: "필기 관련 API"

paths:
  /notes/{noteId}/ai-summary:
    patch:
      tags:
        - Notes
      summary: "AI 요약 정보 업데이트"
      description: |
        노트의 AI 요약 정보를 업데이트합니다.
        
        **Difficulty 변환 로직:**
        - "입문", "초급" → Easy
        - "중급" → Medium
        - "중상급", "고급" → Hard
        - 기타/없음 → Medium (기본값)
        
        **데이터 흐름:**
        1. 프론트엔드에서 AI 서비스 호출 (http://localhost:3001/api/summarize)
        2. AI 서비스 응답 받기
        3. 이 API를 통해 백엔드에 저장
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: noteId
          required: true
          schema:
            type: integer
            format: int64
          description: "업데이트할 노트 ID"
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAiSummaryRequest"
            examples:
              example1:
                summary: "기본 예시"
                value:
                  keyPoints:
                    - "프로세스 개념"
                    - "스레드 동기화"
                    - "데드락 해결"
                  difficulty: "중급"
                  estimatedTime: "1시간"
                  summary: "운영체제의 프로세스와 스레드에 대한 핵심 내용을 다룹니다."
                  tags:
                    - "운영체제"
                    - "프로세스"
                    - "스레드"
              example2:
                summary: "최소 필드만 포함"
                value:
                  summary: "전체 요약 내용만 포함"
      responses:
        "200":
          description: "AI 요약이 성공적으로 업데이트되었습니다."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateAiSummaryResponse"
              example:
                message: "AI 요약이 성공적으로 업데이트되었습니다."
                noteId: 1
                updatedFields:
                  aiSummary: "운영체제의 프로세스와 스레드에 대한 핵심 내용을 다룹니다."
                  difficulty: "Medium"
                  estimatedTime: "1시간"
        "400":
          description: "요청 데이터가 올바르지 않습니다."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: "요청 데이터가 올바르지 않습니다."
                errors:
                  - "difficulty 필드는 '입문', '초급', '중급', '중상급', '고급' 중 하나여야 합니다."
        "401":
          description: "인증이 필요합니다."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: "인증이 필요합니다."
        "403":
          description: "이 노트를 수정할 권한이 없습니다."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: "이 노트를 수정할 권한이 없습니다."
        "404":
          description: "노트를 찾을 수 없습니다."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: "노트를 찾을 수 없습니다."
        "500":
          description: "서버 오류가 발생했습니다."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: "서버 오류가 발생했습니다."

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT 토큰 (노트 업로더만 수정 가능)"
  
  schemas:
    UpdateAiSummaryRequest:
      type: object
      description: "AI 요약 정보 업데이트 요청"
      properties:
        keyPoints:
          type: array
          items:
            type: string
          description: "핵심 내용 리스트 (최대 5개)"
          maxItems: 5
          example:
            - "핵심 포인트 1"
            - "핵심 포인트 2"
            - "핵심 포인트 3"
        difficulty:
          type: string
          enum: ["입문", "초급", "중급", "중상급", "고급"]
          description: "난이도"
          example: "중급"
        estimatedTime:
          type: string
          description: "예상 학습시간 (예: '30분', '1시간')"
          example: "1시간"
        summary:
          type: string
          description: "전체 요약 텍스트 (aiSummary 필드에 저장됨)"
          example: "전체 요약 내용..."
        tags:
          type: array
          items:
            type: string
          description: "태그 리스트 (선택적 구현)"
          example:
            - "태그1"
            - "태그2"
            - "태그3"
      additionalProperties: false
      note: "모든 필드가 선택사항이지만, 최소한 하나의 필드는 포함되어야 합니다."

    UpdateAiSummaryResponse:
      type: object
      description: "AI 요약 정보 업데이트 응답"
      required:
        - message
        - noteId
        - updatedFields
      properties:
        message:
          type: string
          description: "성공 메시지"
          example: "AI 요약이 성공적으로 업데이트되었습니다."
        noteId:
          type: integer
          format: int64
          description: "업데이트된 노트 ID"
          example: 1
        updatedFields:
          type: object
          description: "업데이트된 필드 정보"
          required:
            - aiSummary
            - difficulty
            - estimatedTime
          properties:
            aiSummary:
              type: string
              description: "저장된 전체 요약 (summary 필드 값)"
              example: "전체 요약 내용..."
            difficulty:
              type: string
              enum: ["Easy", "Medium", "Hard"]
              description: "저장된 난이도 (Enum 값)"
              example: "Medium"
            estimatedTime:
              type: string
              description: "저장된 예상 학습시간"
              example: "1시간"

    ErrorResponse:
      type: object
      description: "에러 응답"
      required:
        - message
      properties:
        message:
          type: string
          description: "에러 메시지"
          example: "요청 데이터가 올바르지 않습니다."
        errors:
          type: array
          items:
            type: string
          description: "상세 에러 목록 (선택사항)"
          example:
            - "difficulty 필드는 '입문', '초급', '중급', '중상급', '고급' 중 하나여야 합니다."

